SearchCastCrew/Controllers/ProfileController.cs
using SearchCastCrew.Adapters;
using SearchCastCrew.Data;
using SearchCastCrew.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace SearchCastCrew.Controllers
{
    public class ProfileController : Controller
    {
        private IUserAdapter _adapter;

        public ProfileController()
        {
            _adapter = new UserDataAdapter();
        }
        public ProfileController(IUserAdapter adapter)
        {
            _adapter = adapter;
        }

        public ActionResult Index(string uid)
        {
            //string uid = User.Identity.GetUserId();
            //UserProfileVm pvm = new UserProfileVm();
            //    pvm = _adapter.GetUser(string uid);
            //    return View(pvm);
            var z = uid;
            UserProfileVm pVm = new UserProfileVm();
            pVm = _adapter.GetUser(uid);

            return View(pVm);
        }
    }
}

SearchCastCrew/Controllers/ProfilesController.cs
using SearchCastCrew.Adapters;
using SearchCastCrew.Data;
using SearchCastCrew.Data.Models;
using SearchCastCrew.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SearchCastCrew.Controllers
{
    public class ProfilesController : Controller
    {
        //Move to adapter...
        private ApplicationDbContext db = new ApplicationDbContext();
        IUserAdapter _adapter;

        public ProfilesController()
        {
            _adapter = new UserDataAdapter();
        }

        public ProfilesController(IUserAdapter adp)
        {
            _adapter = adp;
        }



        public ActionResult SearchMap()
        {
            UserIndexVm uVm = new UserIndexVm();
            uVm.UserList = _adapter.GetAllUsersAddresses();

            //string[] addArray;
            return View(uVm);

            //UserIndexVm uvm = new UserIndexVm();
            //uvm.UserList.

            //var applicationUsers = db.Users.Include(a => a.AgeRange).Include(a => a.Availability).Include(a => a.BodyType).Include(a => a.Ethnicity).Include(a => a.EyeColor).Include(a => a.Gender).Include(a => a.HairColor);
            //return View(applicationUsers.ToList());
        }


        [HttpGet]
        public ActionResult Search(int num)
        {
            SearchFilterVm svm = new SearchFilterVm();

            svm.UserList = _adapter.GetAllUsers(num);

            svm.TotalUsers = _adapter.GetAllUserCount();
            svm.UsersPerPage = 6;
            svm.PageCount = svm.TotalUsers / svm.UsersPerPage;

            if ((svm.TotalUsers % svm.UsersPerPage) != 0)
            {
                svm.PageCount++;
            }

            // Set the value of PrevPage
            if (num == 0)
            {
                svm.PrevPage = 0;
            }
            else
            {
                svm.PrevPage = num - 1;
            }

            // Set the value of NextPage
            if (num == svm.PageCount - 1)
            {
                svm.NextPage = num;
            }
            else
            {
                svm.NextPage = num + 1;
            }


            //svm.FirstName = "David";
            //svm.LastName = "Graham";
            //svm.City = "houston";
            //svm.State = "TX";
            //svm.Title = "Producer";
            svm.AgeRangeList = new SelectList(db.AgeRanges, "AgeRangeId", "Name");
            svm.AvailabilityList = new SelectList(db.Availability, "AvailabilityId", "Name");
            svm.BodyTypeList = new SelectList(db.BodyTypes, "BodyTypeId", "Name");
            svm.EthnicityList = new SelectList(db.Ethnicities, "EthnicityId", "Name");
            svm.EyeColorList = new SelectList(db.EyeColors, "EyeColorId", "Color");
            svm.GenderList = new SelectList(db.Genders, "GenderId", "Name");
            svm.HairColorList = new SelectList(db.HairColors, "HairColorId", "Color");
            return View(svm);
        }

        /////

        [HttpPost]
        public ActionResult Search(SearchFilterVm svm)
        {

            SearchFilterVm srvm = new SearchFilterVm();

            srvm = _adapter.FilteredUsers(svm);

            srvm.InSearchMode = true;


            srvm.UsersPerPage = 6;
            srvm.PageCount = srvm.TotalUsers / srvm.UsersPerPage;

            if ((srvm.TotalUsers % srvm.UsersPerPage) != 0)
            {
                srvm.PageCount++;
            }

            if (svm.InDirection == "next")
            {
                if (srvm.CurrPage != srvm.PageCount)
                {
                    srvm.CurrPage = srvm.CurrPage;
                }
                else
                {
                    srvm.CurrPage++;
                }
            }

            if (svm.InDirection == "prev")
            {
                if (srvm.CurrPage != 0)
                {
                    srvm.CurrPage--;
                }
            }

            // Set the value of PrevPage
            if (srvm.CurrPage == 0)
            {
                srvm.PrevPage = 0;
            }
            else
            {
                srvm.PrevPage = srvm.CurrPage - 1;
            }

            // Set the value of NextPage
            if (srvm.CurrPage == svm.PageCount - 1)
            {
                srvm.NextPage = srvm.CurrPage;
            }
            else
            {
                srvm.NextPage = srvm.CurrPage + 1;
            }

            srvm.AgeRangeList = new SelectList(db.AgeRanges.ToList(), "AgeRangeId", "Name", svm.AgeRangeId);
            srvm.AvailabilityList = new SelectList(db.Availability.ToList(), "AvailabilityId", "Name", svm.AvailabilityId);
            srvm.BodyTypeList = new SelectList(db.BodyTypes.ToList(), "BodyTypeId", "Name", svm.BodyTypeId);
            srvm.EthnicityList = new SelectList(db.Ethnicities.ToList(), "EthnicityId", "Name", svm.EthnicityId);
            srvm.EyeColorList = new SelectList(db.EyeColors.ToList(), "EyeColorId", "Color", svm.EyeColorId);
            srvm.GenderList = new SelectList(db.Genders.ToList(), "GenderId", "Name", svm.GenderId);
            srvm.HairColorList = new SelectList(db.HairColors.ToList(), "HairColorId", "Color", svm.HairColorId);

            return View(srvm);

        }

        ///
    }
}

SearchCastCrew/Views/Profiles/Index.cshtml
@using Microsoft.AspNet.Identity
@model SearchCastCrew.Models.UserIndexVm
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<br />
<br />

<div class="container">

    <div class="row clearfix">

        <div class="col-md-12 column">

            <div class="row">
                @foreach (var item in Model.UserList.Take(3))
                {
                    <div class="col-md-4">

                        <div class="thumbnail">
                            @*<img alt="300x200" src="@item.ImageUrl.FirstOrDefault().ImgUrl.FirstOrDefault()" />*@
                            <div class="caption">
                                <h3>
                                    @item.FirstName, @item.LastName
                                </h3>
                                <p>
                                    @item.Title, @item.State
                                </p>
                                <p>
                                    @Html.ActionLink("View", "ViewProfile", "Home", new { uid = User.Identity.GetUserId() }, new { @class = "btn btn-primary" });
                                    <a class="btn btn-primary" href="#">View </a> <a class="btn" href="#">Contact</a>
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row">
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/people" />
                        <div class="caption">
                            <h3>
                                Jane Smith
                            </h3>
                            <p>
                                - Tittle Sr Deirtecot
                                - Dallas Ta=X
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">View </a> <a class="btn" href="#">Contact</a>
                            </p>
                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/city" />
                        <div class="caption">
                            <h3>
                                Thumbnail label
                            </h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                            </p>
                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/sports" />
                        <div class="caption">
                            <h3>
                                Thumbnail label
                            </h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">


            <div class="row">
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/people" />
                        <div class="caption">
                            <h3>
                                Thumbnail label
                            </h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                            </p>
                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/city" />
                        <div class="caption">
                            <h3>
                                Thumbnail label
                            </h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                            </p>
                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="http://lorempixel.com/600/200/sports" />
                        <div class="caption">
                            <h3>
                                Thumbnail label
                            </h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                            <p>
                                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">
            <ul class="pagination">
                <li>
                    <a href="#">Prev</a>
                </li>
                <li>
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">Next</a>
                </li>
            </ul>
        </div>
    </div>

</div>

SearchCastCrew/Views/Profiles/Search.cshtml
@model SearchCastCrew.Models.SearchFilterVm

@{
    ViewBag.Title = "Search For talent";
}
<!-- Latest compiled and minified CSS -->
<link href="css/bootstrap.css" rel="stylesheet" />
<!-- Tiles theme CSS -->
<link href="/css/Style.css" rel="stylesheet" />
<!--Sidebar CSS-->
<link href="css/simple-sidebar.css" rel="stylesheet" />
<!--Social Fonts-->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<br /><br /><br /><br /><br /><br />

<div class="container">


    <div class="row">
        <div class="col-2 col-sm-2 col-lg-2">

            <h2>Search Talent</h2>

            @using (Html.BeginForm())
            {
                <div class="form-horizontal">

                    <hr />
                    @Html.HiddenFor(model => model.CurrPage)
                                        @Html.HiddenFor(model => model.NextPage)
                                                            @Html.HiddenFor(model => model.PrevPage)
                                                            @Html.HiddenFor(model => model.InDirection)






                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control input-sm talent-input" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control input-sm" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control  input-sm" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control  input-sm" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control  input-sm" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.HeightInInches, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HeightInInches, new { htmlAttributes = new { @class = "form-control  input-sm" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control  input-sm" } })
                        </div>
                    </div>                   

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.AgeRangeId, "Age Range", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.AgeRangeId, Model.AgeRangeList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.HairColorId, "Hair Color", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.HairColorId, Model.HairColorList, "", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.EyeColorId, "Eye Color", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.EyeColorId, Model.EyeColorList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.GenderId, "Gender", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.GenderId, Model.GenderList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.BodyTypeId, "Body Type", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.BodyTypeId, Model.BodyTypeList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.EthnicityId, "Ethnicity", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.EthnicityId, Model.EthnicityList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        @Html.LabelFor(model => model.AvailabilityId, "Availability", htmlAttributes: new { @class = "search-control-label col-md-7" })
                        <br />
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.AvailabilityId, Model.AvailabilityList, "", htmlAttributes: new { @class = "form-control  input-sm" })
                        </div>
                    </div>

                    <br />
                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="text-center">
                                <input type="submit" value="Search" class="btn btn-default" />
                                <br />
                                <br />
                                <a href="@Url.Action("Search", "Profiles", new { num = 0 })" class="btn btn-default">Reset Form</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>



        <div class="col-9 col-sm-9 col-lg-9 right">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="row">
                        @foreach (var item in Model.UserList)
                        {
                            <div class="col-md-4 col-search-height">
                                <div class="thumbnail">
                                    @if (@item.ImageUrl == null)
                                    {
                                        <img alt="300x200" src="http://www.trialguides.com/images/authors/placeholder.jpg" />
                                    }
                                    else
                                    {
                                        <img alt="300x200" src="@item.ImageUrl.ImgUrl" />
                                    }
                                    <div class="caption">
                                        <h3>
                                            @item.FirstName @item.LastName
                                        </h3>
                                        <p>
                                            <span class="glyphicon glyphicon-briefcase"></span> @item.Title<br />
                                            <span class="glyphicon glyphicon-map-marker"></span> @item.City, @item.State
                                        </p>
                                        <p>
                                            <a class="btn btn-primary" href="@Url.Action("ViewProfile", "Home", new { uid = item.UserId })">View Profile</a> @*<a class="btn" href="#">Contact</a>*@
                                        </p>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12 column">
                    @if (Model.InSearchMode)
                    {
                        <p>Total Profiles: @Model.TotalUsers</p>
                        <ul class="pagination">
                            <li>
                                <a id="btn_prev" pageJump="@Model.PrevPage" href="@Url.Action("Search", "Profiles" )">Prev</a>
                            </li>
                            @for (int i = 0; i < Model.PageCount; i++)
                            {
                                <li>
                                    <a class="btn_jump" pageJump="@i" href="@Url.Action("Search", "Profiles" )">@(i + 1)</a>
                                </li>
                            }
                            <li>
                                <a id="btn_next" pageJump="@Model.NextPage" href="@Url.Action("Search", "Profiles" )">Next</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <p>Total Profiles: @Model.TotalUsers</p>
                        <ul class="pagination">
                            <li>
                                <a href="@Url.Action("Search", "Profiles", new { num = Model.PrevPage } )">Prev</a>
                            </li>
                            @for (int i = 0; i < Model.PageCount; i++)
                            {
                                <li>
                                    <a href="@Url.Action("Search", "Profiles", new { num = i } )">@(i + 1)</a>
                                </li>
                            }
                            <li>
                                <a href="@Url.Action("Search", "Profiles", new { num = Model.NextPage } )">Next</a>
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<style>
    .input-sm {
        height: 26px;
    }

    .form-group {
        margin-bottom: 0;
    }

    select.input-sm {
        height: 29px;
    }
</style>

<script>
    $("#btn_prev").click(function (event) {
        event.preventDefault();
        $('#InDirection').val("prev");
        var jNum = $(this).attr("pageJump")
        $('#CurrPage').val(jNum)
        document.forms[0].submit();
    });
    $("#btn_next").click(function (event) {
        event.preventDefault();
        $('#InDirection').val("next");
        var jNum = $(this).attr("pageJump")
        $('#CurrPage').val(jNum)
        document.forms[0].submit();
    });
    $(".btn_jump").click(function (event, nums) {
        // $('#InDirection').val("next");
        event.preventDefault();
        $('#InDirection').val("jump");
        var jNum = $(this).attr("pageJump")
        $('#CurrPage').val(jNum)
        console.log(jNum)
        document.forms[0].submit();
    });


</script>